<a href="https://colab.research.google.com/github/Adriungs/TALENTO_TECH_CIENCIA_DE_DATOS/blob/main/1.CARGA%20DE%20DATOS/1_Carga_de_datos_credit_risk_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center><font size= "5" ><u>CARGA DE DATOS FORMA 1</u></font></center>
En este caso probamos si tenemos el dataset local con un bucle if... En caso de que no lo encuentre podemos dirigirnos directamente a la página en este caso de kaggle con else donde descargamos el dataset de laotse "laotse/credit-risk-dataset"(nombre del creador/nombre del dataset).

Este método nos permite verificar si tenemos el archivo tanto localmente, pero si por algún motivo se nos perdió el archivo o se cambio de lugar, el código automáticamente lo va a buscar directamente en la página donde se descarga

Esto es para cargas de datos de trabajos donde se use el dataset por un tiempo hasta llegar a una conclusión. Esto es bastante importante tambíen para conectar diferentes fuentes de datos sin tener que andar haciendo trabajo de más moviendo y descargando datasets de forma poco práctica.

In [2]:
import pandas as pd
import os

ruta_local = "/content/bank.csv"
if os.path.exists(ruta_local):
  ruta_csv = ruta_local
else:
  import kagglehub

  ruta_dataset = kagglehub.dataset_download("laotse/credit-risk-dataset") #Aca se guarda en una carpeta llamada ruta_dataset
  ruta_csv = os.path.join(ruta_dataset, "credit_risk_dataset.csv") #Aca une ó junta la carpeta con el archivo que buscamos de forma segura

Using Colab cache for faster access to the 'credit-risk-dataset' dataset.

In [9]:
bank = pd.read_csv(ruta_csv, sep =",")
print("Dataset cargado correctamente")

Dataset cargado correctamente

In [12]:
display(bank.head())

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

<center><font size= "5" ><u>CARGA DE DATOS FORMA 2</u></font></center>
Esto es para trabajo temporal, no muy usado. Ya que siempre el dataset se tiene que volver a subir, es poco práctico poco usado. Se carga el dataset en la solapa de archivos y es unicamente local y temporal.
Se suele usar como enseñanza de códigos o para una examinación muy rapida

In [15]:
import pandas as pd
df = pd.read_csv("credit_risk_dataset.csv", sep = ",")
print("Dataset cargado correctamente")

Dataset cargado correctamente

<center><font size= "5" ><u>CARGA DE DATOS FORMA 3</u></font></center>
Esta es la forma más complicada pero la más segura. Aunque se usa solo para proyectos que tienen que durar varios años en porfolios. Si la página donde extraiste el archivo se encuentra caida, podes cargarla desde tu github guardando el dataset entonces cuando una persona ejecute tu código el dataset se va a ejecutar desde tu propia página.

Lo complicado es guardar cada dataset en github

In [17]:
import pandas as pd

#definimos la ruta
url = "https://raw.githubusercontent.com/Adriungs/credit-risk-analysis-pandas/refs/heads/main/data/credit_risk_dataset.csv"

#Leer
tabla = pd.read_csv(url)

tabla.head(5)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

<center><font size= "5" ><u>CARGA DE DATOS FORMA 4</u></font></center>
También podemos usar todas las formas anteriores en un mismo código con if/else pero con try y except.
Es la menos usada de todas pero es muy segura aunque lleva mucho trabajo de carga y es improductivo hacerlo de esta forma

In [20]:
import pandas as pd
import os
import kagglehub

ruta_local = "/content/bank.csv"
url_github = "https://raw.githubusercontent.com/Adriungs/credit-risk-analysis-pandas/refs/heads/main/data/credit_risk_dataset.csv"

# 1. Intenta leer el archivo local primero
if os.path.exists(ruta_local):
    print("Cargando archivo local...")
    tabla = pd.read_csv(ruta_local)

# 2. Si no es local, intenta descargarlo de GitHub (método rápido)
else:
    try:
        print("Intentando cargar desde GitHub...")
        tabla = pd.read_csv(url_github)

    # 3. Si falla GitHub (por falta de internet o URL caída), usa Kagglehub
    except Exception:
        print("GitHub no disponible. Descargando desde Kaggle...")
        ruta_dataset = kagglehub.dataset_download("laotse/credit-risk-dataset")
        ruta_csv = os.path.join(ruta_dataset, "credit_risk_dataset.csv")
        tabla = pd.read_csv(ruta_csv)

# Mostrar las primeras filas para verificar el éxito
print("¡Datos cargados con éxito!")
tabla.head()

Intentando cargar desde GitHub...
¡Datos cargados con éxito!

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4