<a href="https://colab.research.google.com/github/Adriungs/TALENTO_TECH_CIENCIA_DE_DATOS/blob/main/3.PREPROCESAMIENTO%20Y%20PREPARACI%C3%93N%20DE%20DATOS/3_ML_FEATURE_ENGINEERING_Y_TRANSFORMACI%C3%93N_DE_DATOS_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#FEATURE ENGINEERING Y TRANSFORMACIÓN DE DATOS

##Conjunto de datos elegido

In [68]:
import pandas as pd

# URL del archivo raw en GitHub
url_github = "https://raw.githubusercontent.com/Adriungs/TALENTO_TECH_CIENCIA_DE_DATOS/main/2.%20ANALISIS_DE_DATOS/credit_risk_limpio.csv"

# Lectura directa desde la URL
tabla = pd.read_csv(url_github)

# Verificar la carga
tabla.head()

,id_cliente,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_amnt_log,rango_edad,estado_nombre,rango_tasa,rango_historial
0,2,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2,6.908755,18-25,No Default (0),Tasa Media,0-3 años (Corto)
1,3,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3,8.612685,18-25,Default (1),Tasa Alta,0-3 años (Corto)
2,4,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2,10.463132,18-25,Default (1),Tasa Alta,0-3 años (Corto)
3,5,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4,10.463132,18-25,Default (1),Tasa Alta,4-6 años (Medio)
4,6,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2,7.824446,18-25,Default (1),Tasa Baja,0-3 años (Corto)

##EXPLORACIÓN INICIAL DEL CONJUNTO DE DATOS

In [69]:
print("Dimensiones del dataset:", tabla.shape)
print("\nColumnas disponibles:")
print(tabla.columns.tolist())

Dimensiones del dataset: (30792, 18)

Columnas disponibles:
['id_cliente', 'person_age', 'person_income', 'person_home_ownership', 'person_emp_length', 'loan_intent', 'loan_grade', 'loan_amnt', 'loan_int_rate', 'loan_status', 'loan_percent_income', 'cb_person_default_on_file', 'cb_person_cred_hist_length', 'loan_amnt_log', 'rango_edad', 'estado_nombre', 'rango_tasa', 'rango_historial']

In [70]:
tabla.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30792 entries, 0 to 30791
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id_cliente                  30792 non-null  int64
 1   person_age                  30792 non-null  int64
 2   person_income               30792 non-null  int64
 3   person_home_ownership       30792 non-null  object
 4   person_emp_length           30792 non-null  float64
 5   loan_intent                 30792 non-null  object
 6   loan_grade                  30792 non-null  object
 7   loan_amnt                   30792 non-null  int64
 8   loan_int_rate               30792 non-null  float64
 9   loan_status                 30792 non-null  int64
 10  loan_percent_income         30792 non-null  float64
 11  cb_person_default_on_file   30792 non-null  object
 12  cb_person_cred_hist_length  30792 non-null  int64
 13  loan_amnt_log               30792 non-null  float64
 14  rango_edad                  30792 non-null  object
 15  estado_nombre               30792 non-null  object
 16  rango_tasa                  30792 non-null  object
 17  rango_historial             30792 non-null  object
dtypes: float64(4), int64(6), object(8)
memory usage: 4.2+ MB

##SELECCIÓN DE COLUMNAS

###LAS VARIABLES CON MAYOR IMPACTO

loan_percent_income (Porcentaje del ingreso comprometido):

Impacto: Muy Alto (Causa Primaria). Es el predictor directo con mayor capacidad explicativa. Cuando la cuota supera el 20% (0.20) de los ingresos del cliente, la probabilidad de incumplimiento se dispara exponencialmente, sin importar otras características del solicitante.

cb_person_default_on_file( personas con incumplimiento registrado/ mora historica).

Impacto: Muy Alto(Causa directa).
Los que tienen historial crediticio N de incumplimiento el 19,51% suele volver a no pagar.


loan_intent (Destino o intención del préstamo):

Impacto: Alto. Separa de manera tajante el riesgo según la motivación financiera. Destinos de urgencia o estrés económico como DEBTCONSOLIDATION y MEDICAL registran las tasas de mora más elevadas (27%- 28% ), mientras que inversiones a futuro (VENTURE, EDUCATION) registran los valores más bajos (~15%- 17%).

cb_person_default_on_file (Antecedente previo de incumplimiento):

Impacto: Alto (Factor Multiplicador). Actúa como un multiplicador directo de riesgo. Contar con un antecedente negativo (Y) eleva sustancialmente la tasa de mora real en cualquier segmento o calificación crediticia en comparación con un historial impecable (N).

loan_int_rate (Tasa de interés del préstamo):

Impacto: Alto (Presión de Costo). Tasas elevadas (>13%) imponen una carga financiera adicional sobre la cuota que termina sofocando la capacidad de pago del prestatario y acelerando su caída en default.

loan_grade (Calificación o scoring interno de riesgo):

Impacto: Medio - Alto. Demuestra una alta correlación con el default real (los grados 'A' y 'B' mantienen mora baja, mientras que 'D' a 'G' concentran la mayor mora), actuando como una síntesis de la evaluación previa del banco.

person_home_ownership (Situación habitacional):

Impacto: Medio. Los inquilinos (RENT) y quienes poseen hipoteca activa (MORTGAGE) muestran menor margen de absorción ante imprevistos económicos en comparación con los propietarios directos (OWN).

cb_person_cred_hist_length (Antigüedad del historial crediticio):

Impacto: Medio - Bajo. Un historial muy corto (0 a 3 años) genera asimetría de información y aumenta la tasa de default, aunque su efecto es secundario en comparación con la capacidad de pago (loan_percent_income) y los antecedentes previos (cb_person_default_on_file).

loan_percent_income

cb_person_default_on_file

loan_intent

loan_int_rate

loan_grade

person_home_ownership

cb_person_cred_hist_length

- loan_percent_income, que indica la proporción del ingreso de la persona destinada al préstamo. Será útil para explorar escalado, distribución de valores y posibles valores extremos.

- cb_person_default_on_file, que indica si la persona tiene antecedentes de incumplimiento registrados. Al ser una variable categórica binaria, permitirá trabajar con técnicas de codificación como Label Encoding.

- loan_intent, que representa el propósito del préstamo. Servirá para ejemplificar la transformación de variables categóricas mediante One-Hot Encoding.

- loan_int_rate, que indica la tasa de interés del préstamo. Al ser una variable numérica, permitirá explorar escalado y distribución, además de evaluar posibles valores extremos.

- loan_grade, que representa la calificación asignada al préstamo. Permitirá trabajar con la codificación de categorías ordenadas, teniendo en cuenta que sus categorías tienen un orden natural.

- person_home_ownership, que indica la situación habitacional de la persona, por ejemplo, si alquila o es propietaria. Servirá para practicar One-Hot Encoding, ya que representa categorías sin un orden numérico natural.

- cb_person_cred_hist_length, que indica la antigüedad del historial crediticio de la persona en años. Será útil para explorar la distribución de una variable numérica y crear atributos derivados, si el análisis lo justifica.

In [71]:
# Guardar la lista de columnas
columnas = [
    'loan_percent_income',
    'cb_person_default_on_file',
    'loan_intent',
    'person_income',
    'loan_int_rate',
    'loan_grade',
    'person_home_ownership',
    'cb_person_cred_hist_length',
    'loan_status'

]

# Crear un nuevo DataFrame filtrado usando tabla
df= tabla[columnas].copy()

# Ver las primeras filas
df.head()

,loan_percent_income,cb_person_default_on_file,loan_intent,person_income,loan_int_rate,loan_grade,person_home_ownership,cb_person_cred_hist_length,loan_status
0,0.10,N,EDUCATION,9600,11.14,B,OWN,2,0
1,0.57,N,MEDICAL,9600,12.87,C,MORTGAGE,3,1
2,0.53,N,MEDICAL,65500,15.23,C,RENT,2,1
3,0.55,Y,MEDICAL,54400,14.27,C,RENT,4,1
4,0.25,N,VENTURE,9900,7.14,A,OWN,2,1


* Personales:
   * person_home_ownership → situación habitacional.

* Financieras / del préstamo:

   * loan_percent_income → proporción del ingreso destinada al préstamo.

  * loan_int_rate → tasa de interés.

   * loan_intent → propósito del préstamo.
* Caracteristica del prestamo:
   
   * loan_intent → intención o propósito del prestamo
* Crediticias:

   * loan_grade → calificación del préstamo.
   * cb_person_default_on_file → antecedente de incumplimiento.
   * cb_person_cred_hist_length → antigüedad del historial crediticio.
* Objetivo:

   * loan_status → estado del préstamo / incumplimiento.

##TRANSFORMACIÓN DE VARIABLES CATEGÓRICAS

Muchas veces los conjuntos de datos incluyen variables categóricas, es decir, columnas cuyos valores representan clases o categorías, como nivel educativo o estado civil.

Como la mayoría de los modelos de Machine Learning trabajan con números, estas variables suelen necesitar alguna transformación previa. Dos de las técnicas más comunes son Label Encoding y One-Hot Encoding.

###REVISIÓN DE CATEGORÍAS

Antes de aplicar una transformación, conviene observar qué valores aparecen en cada variable categórica. Esto nos permite entender mejor la información disponible y verificar qué categorías serán codificadas.

In [72]:
print("Valores únicos en Person_default:")
print(df["cb_person_default_on_file"].unique())

print("\nValores únicos en loan_intent:")
print(df["loan_intent"].unique())

print("\nValores únicos en loan_grade:")
print(df["loan_grade"].unique())

print("\nValores únicos en person_home_ownership:")
print(df["person_home_ownership"].unique())

Valores únicos en Person_default:
['N' 'Y']

Valores únicos en loan_intent:
['EDUCATION' 'MEDICAL' 'VENTURE' 'PERSONAL' 'HOMEIMPROVEMENT'
 'DEBTCONSOLIDATION']

Valores únicos en loan_grade:
['B' 'C' 'A' 'E' 'F' 'D' 'G']

Valores únicos en person_home_ownership:
['OWN' 'MORTGAGE' 'RENT' 'OTHER']

###LABEL ENCODING

El Label Encoding consiste en reemplazar cada categoría por un número entero.

Es una transformación simple y útil en algunos casos, aunque hay que aplicarla con cuidado: al convertir categorías en números, puede dar la impresión de que existe un orden entre ellas, incluso cuando ese orden no tiene sentido real.

label_grade es la columna ya preprocesada

loan_grade = label_grade

pero una preparada para el modelo

In [73]:
from sklearn.preprocessing import LabelEncoder

# Creamos el codificador
codif_grade = LabelEncoder()

# Generamos una nueva columna codificada
df["label_grade"] = codif_grade.fit_transform(df["loan_grade"])

# Mostramos la correspondencia entre categorías y números
mapeo_grade = dict(zip(codif_grade.classes_, codif_grade.transform(codif_grade.classes_)))
print("Codificación aplicada en loan_grade:")
print(mapeo_grade)

df[["loan_grade", "label_grade"]].head(10)

Codificación aplicada en loan_grade:
{'A': np.int64(0), 'B': np.int64(1), 'C': np.int64(2), 'D': np.int64(3), 'E': np.int64(4), 'F': np.int64(5), 'G': np.int64(6)}

  loan_grade  label_grade
0          B            1
1          C            2
2          C            2
3          C            2
4          A            0
5          B            1
6          B            1
7          A            0
8          B            1
9          A            0

In [74]:
df.drop(columns=["label_grade"], inplace=True)

###ONE-HOT ENCODING

 Esta transformación generará una nueva columna binaria para cada categoría posible, indicando con 1 si esa categoría está presente y con 0 en caso contrario.

In [75]:
df_intent = pd.get_dummies(df["loan_intent"], prefix="col_intent")

# Mostramos las primeras filas
df_intent.head()

,col_intent_DEBTCONSOLIDATION,col_intent_EDUCATION,col_intent_HOMEIMPROVEMENT,col_intent_MEDICAL,col_intent_PERSONAL,col_intent_VENTURE
0,False,True,False,False,False,False
1,False,False,False,True,False,False
2,False,False,False,True,False,False
3,False,False,False,True,False,False
4,False,False,False,False,False,True

###COMPARACIÓN CON LA VARIABLE ORIGINAL

Para entender mejor el resultado, en la siguiente celda vamos a mostrar la columna original junto con las nuevas columnas generadas por el One-Hot Encoding.

In [76]:
pd.concat(
    [df[["loan_intent"]].head(10),   #variable_original
    df_intent.head(10)],             #variable_transform
    axis=1
)

,loan_intent,col_intent_DEBTCONSOLIDATION,col_intent_EDUCATION,col_intent_HOMEIMPROVEMENT,col_intent_MEDICAL,col_intent_PERSONAL,col_intent_VENTURE
0,EDUCATION,False,True,False,False,False,False
1,MEDICAL,False,False,False,True,False,False
2,MEDICAL,False,False,False,True,False,False
3,MEDICAL,False,False,False,True,False,False
4,VENTURE,False,False,False,False,False,True
5,EDUCATION,False,True,False,False,False,False
6,MEDICAL,False,False,False,True,False,False
7,PERSONAL,False,False,False,False,True,False
8,VENTURE,False,False,False,False,False,True
9,HOMEIMPROVEMENT,False,False,True,False,False,False

A diferencia del Label Encoding, el One-Hot Encoding no reemplaza cada categoría por un único número. En cambio, crea una representación binaria que evita introducir un orden artificial entre las categorías.

Por eso, suele ser una alternativa más adecuada cuando trabajamos con variables categóricas sin jerarquía natural.

---

###NORMALIZACIÓN (MIN-MAX SCALING)

En la siguiente celda vamos a aplicar normalización, una técnica que transforma los valores para que queden dentro de un rango acotado, generalmente entre 0 y 1.

Esto resulta útil cuando queremos comparar variables en una misma escala o cuando el modelo es sensible a las diferencias de magnitud.

In [77]:
from sklearn.preprocessing import MinMaxScaler

# Creamos el escalador
escalador_minmax = MinMaxScaler()

# Generamos una nueva columna normalizada
df["Income_Normalizado"] = escalador_minmax.fit_transform(df[["person_income"]])

df[["person_income", "Income_Normalizado"]].head(10)

   person_income  Income_Normalizado
0           9600            0.000934
1           9600            0.000934
2          65500            0.010257
3          54400            0.008406
4           9900            0.000984
5          77100            0.012191
6          78956            0.012501
7          83000            0.013175
8          85000            0.013509
9          10000            0.001001

---
###ESTANDARIZACIÓN (Z-SCORE SCALING)


Ahora vamos a aplicar estandarización. A diferencia de la normalización, esta técnica no lleva los datos a un rango fijo, sino que los transforma para que tengan media 0 y desvío estándar 1.

Esto permite expresar cada valor en función de qué tan alejado está del promedio.

In [78]:
from sklearn.preprocessing import StandardScaler
escalador_standard = StandardScaler()

# Generamos una nueva columna estandarizada
df["Income_Estandarizado"] = escalador_standard.fit_transform(df[["person_income"]])

df[["person_income", "Income_Estandarizado"]].head(10)

   person_income  Income_Estandarizado
0           9600             -0.907296
1           9600             -0.907296
2          65500             -0.018672
3          54400             -0.195125
4           9900             -0.902527
5          77100              0.165729
6          78956              0.195234
7          83000              0.259520
8          85000              0.291313
9          10000             -0.900938

###COMPARACIÓN DE RESULTADOS

Comparación de resultados
En la siguiente celda vamos a comparar la variable original con sus versiones normalizada y estandarizada, para observar cómo cambia su escala.

In [79]:
df[["person_income", "Income_Normalizado", "Income_Estandarizado"]].head(10)

   person_income  Income_Normalizado  Income_Estandarizado
0           9600            0.000934             -0.907296
1           9600            0.000934             -0.907296
2          65500            0.010257             -0.018672
3          54400            0.008406             -0.195125
4           9900            0.000984             -0.902527
5          77100            0.012191              0.165729
6          78956            0.012501              0.195234
7          83000            0.013175              0.259520
8          85000            0.013509              0.291313
9          10000            0.001001             -0.900938

In [80]:
df.drop(columns=["Income_Normalizado", "Income_Estandarizado"], inplace=True)

df.columns

Index(['loan_percent_income', 'cb_person_default_on_file', 'loan_intent',
       'person_income', 'loan_int_rate', 'loan_grade', 'person_home_ownership',
       'cb_person_cred_hist_length', 'loan_status'],
      dtype='object')